language: python
install: true
script: true
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: help50
  env: help50
  bucket_name: travis50
  on:
    branch: main
notifications:
  slack:
    secure: mvJ4VOX8toJRvCYdba1SUmR9/iW4Lo8nWG1WBAF95cdo9SCttkNqT68zkL4HI3QG0O6UfQuQ5J9dCMJ+Pp6ROkCwoWmBOifEo/9JDcwEqZ1bZflQrFp6XDV/gEaCDC6NXUusmM83AV3rzO8/1p0Vp9IFXWHoUc4TaOKKfUpfSm680AGU9xaWUkQoXiuju7EAPFdoxBNkuEF7aDzVmYNF6HH8vzOe0X8kkw79UmGmLBs/LKp+85NRq5ZTj4aIiHTM+lahuQ5RjGKyxJ5ETgMieXEqZbE9EZ80OjaIWvq31esrDTHfVZG+eEfiC58HNxmOINUqHdXxWeezuUGYF5Oevdt9VE9LrKu2YeuUXGJWZP8s9wAJUdlvSIc2Fj3aNqNvcNqaBF2EmhsbY2ZpkbxPtK1nhHoGPeQm7ZCxaF4YlRm8v4s+2edxI4a21rplf8IFhy0mWAO81kUOvam5G0ciIgYwt8XJhTDElCgAQT47WyM1sZTlTW5Iyg0YHxiNPu9CTfb08Pwj+coOo9dJdlEUP2Vpxsr336oRdoU48VXG93LRssL/lZsc6hN3PXmHH6woM3hmbd4Jfnl6rPyrUcA+Cdn5xAiN4w3YzwFMA8HDQNmy7j6KRj2rLqU+KGuOGFgcJJCLlotDCKlE3aRovx6DduoiFCiVbQkT7M5B/IMb4Rc=
